// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SawacoApi.Intrastructure.Context;

#nullable disable

namespace SawacoApi.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.BatteryHistory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GPSDeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BatteryHistories");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.Customer", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneNumber");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.DevicePositionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GPSDeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GPSDeviceId");

                    b.ToTable("DevicePositionHistories");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.GPSDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Battery")
                        .HasColumnType("float");

                    b.Property<string>("Bluetooth")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SMSNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Stolen")
                        .HasColumnType("bit");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerPhoneNumber");

                    b.ToTable("GPSDevices");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.GPSObject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Connected")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GPSDeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SafeRadius")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerPhoneNumber");

                    b.ToTable("GPSObjects");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAcknowledge")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerPhoneNumber");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.ObjectPositionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GPSObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GPSObjectId");

                    b.ToTable("ObjectPositionHistories");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.StolenLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Battery")
                        .HasColumnType("float");

                    b.Property<string>("GPSDeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longtitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GPSDeviceId");

                    b.ToTable("StolenLines");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.DevicePositionHistory", b =>
                {
                    b.HasOne("SawacoApi.Intrastructure.Models.GPSDevice", "GPSDevice")
                        .WithMany("DevicePositionHistories")
                        .HasForeignKey("GPSDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GPSDevice");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.GPSDevice", b =>
                {
                    b.HasOne("SawacoApi.Intrastructure.Models.Customer", "Customer")
                        .WithMany("GPSDevices")
                        .HasForeignKey("CustomerPhoneNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.GPSObject", b =>
                {
                    b.HasOne("SawacoApi.Intrastructure.Models.Customer", "Customer")
                        .WithMany("GPSObjects")
                        .HasForeignKey("CustomerPhoneNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.Notification", b =>
                {
                    b.HasOne("SawacoApi.Intrastructure.Models.Customer", "Customer")
                        .WithMany("Notification")
                        .HasForeignKey("CustomerPhoneNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.ObjectPositionHistory", b =>
                {
                    b.HasOne("SawacoApi.Intrastructure.Models.GPSObject", "GPSObject")
                        .WithMany("ObjectPositionHistories")
                        .HasForeignKey("GPSObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GPSObject");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.StolenLine", b =>
                {
                    b.HasOne("SawacoApi.Intrastructure.Models.GPSDevice", "GPSDevice")
                        .WithMany("StolenLines")
                        .HasForeignKey("GPSDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GPSDevice");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.Customer", b =>
                {
                    b.Navigation("GPSDevices");

                    b.Navigation("GPSObjects");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.GPSDevice", b =>
                {
                    b.Navigation("DevicePositionHistories");

                    b.Navigation("StolenLines");
                });

            modelBuilder.Entity("SawacoApi.Intrastructure.Models.GPSObject", b =>
                {
                    b.Navigation("ObjectPositionHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
